services:
  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION}
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - portfolio-ai
  rag:
    build:
      context: ./portfolio-rag
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    container_name: portfolio-rag
    restart: unless-stopped
    depends_on:
      - qdrant
    networks:
      - portfolio-ai
  stt:
    build:
      context: ./stt
      args:
        - ROCM_PYTORCH_VERSION=${ROCM_PYTORCH_VERSION}
    container_name: stt
    restart: unless-stopped
    volumes:
      - ./stt/app:/app
    networks:
      - portfolio-ai

volumes:
  qdrant_data:

networks:
  portfolio-ai:
    driver: bridge
